<?php

/**
 * @file
 * Contains hub_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hub_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hub_test module.
    case 'help.page.hub_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test Hub hooks and functions') . '</p>';
      return $output;

    default:
  }
}

function hub_test_hub_cron_testimonial( $data ) {
  return '30 1 * * *';

}

function hub_test_hub_update_testimonial( $data ) {
  return false;
}

function hub_test_hub_cron_campus( $data ) {
  return '0 2 * * *';
}

function hub_test_hub_update_campus( $data ) {
  return true;
}
